//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart_ShoppingCartItems
    {
        public int Id { get; set; }
        public int ShoppingCartId { get; set; }
        public int ShoppingCartItemId { get; set; }
    
        public virtual ShoppingCart ShoppingCart { get; set; }
        public virtual ShoppingCartItem ShoppingCartItem { get; set; }
    }
}
